version: "3"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    network_mode: bridge
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - "conf.d:/etc/nginx/conf.d:rw"
      - "vhost.d:/etc/nginx/vhost.d:rw"
      - "html:/usr/share/nginx/html:rw"
      - "certs:/etc/nginx/certs:ro"
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ping -c1 localhost
  docker-gen:
    container_name: docker-gen
    image: jwilder/docker-gen
    network_mode: bridge
    command: "-notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:rw"
      - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      - "conf.d:/etc/nginx/conf.d:rw"
      - "vhost.d:/etc/nginx/vhost.d:rw"
      - "html:/usr/share/nginx/html:rw"
      - "certs:/etc/nginx/certs:ro"
    healthcheck:
      test: ping -c1 localhost
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - "NGINX_DOCKER_GEN_CONTAINER=docker-gen"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "conf.d:/etc/nginx/conf.d:rw"
      - "vhost.d:/etc/nginx/vhost.d:rw"
      - "html:/usr/share/nginx/html:rw"
      - "certs:/etc/nginx/certs:rw"
    healthcheck:
      test: ping -c1 localhost

volumes:
  vhost.d:
  conf.d:
  html:
  certs:
